pipeline:
  build:
    image: ubuntu:14.04
    environment:
      - CFLAGS=${CFLAGS}
    commands:
    # set lang for unicode support
      - export LC_ALL=C.UTF-8
    # bingehack prep
      - apt-get update -qq
      - apt-get install -qq git cmake ninja-build clang python uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config libblocksruntime-dev libcurl4-openssl-dev autoconf libtool systemtap-sdt-dev tzdata
      - utils/build-script -r
      - utils/build-script -t
